void main() async {
  print("Inicio del programa");

  try {
    final valueGet = await httpGet("https://domain.org");
    print(valueGet);

    final valuePost = await httpPost("https://domain.org");
    print(valuePost);
  } on Exception catch (err) {
    print("ðŸ‘‹ Tenemos una excepciÃ³n. $err");
  } catch (err) {
    print('Error: $err');
  } finally {
    print("Proceso terminado");
  }

  print("Fin del programa");
}

Future<String> httpGet(String urml) async {
  await Future.delayed(const Duration(seconds: 1));
  return "PeticiÃ³n GET finalizada";
}

Future<String> httpPost(String urml) async {
  await Future.delayed(const Duration(seconds: 1));
  throw Exception("ExcepciÃ³n generada en POST");
}
